# Site settings
title:          robpaulx
description:    "Simple work related blog"
url:            https://pauler285.github.io

# Author
author:
  name:         Robert Paul
  email:        n/a
  url:          https://github.com/inelaah/rain

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Related posts settings
related_posts_section:
  max_count:        5
  min_common_tags:  2

# Links to social media
social:
  github: https://github.com/pauler285
  twitter: https://twitter.com/ItsPauler
  linkedin: https://www.linkedin.com/in/robert-paul-62b5a2b4/
  xing: https://www.xing.com/profile/Robert_Paul/cv
